### PR TITLE
Fix http

### PR DESCRIPTION
**Pull request by TapiocaFox**
Hi I am the student of class IoT. It seems that there are 2 bugs in NodeMCU IoTtalk.

1. First one this that “push" function should have “http.end()”. Otherwise next http operation will occur error.

int push(char *df_name, String value){
    …
    http.end(); // not added before
    return httpCode;
}

2. Second one is "pull" function “get_ret_str” should shrink whitespaces. Or it will interpret wrong. It might be caused by new protocol’s JSON layout below.

Server: 140.113.199.189:9999

Output:

17:58:24.953 -> output D1~: 
17:58:24.953 -> {
17:58:24.953 ->   "samples": [
17:58:24.953 ->     [
17:58:24.953 ->       "2018-12-25 17:58:24.758523", 
17:58:24.953 ->       [
17:58:24.953 ->         227.1036334078388
17:58:24.953 ->       ]
17:58:24.989 ->     ], 
17:58:24.989 ->     [
17:58:24.989 ->       "2018-12-25 17:58:24.523437", 
17:58:24.989 ->       [
17:58:24.989 ->         209.7977152168112
17:58:24.989 ->       ]
17:58:24.989 ->     ]
17:58:24.989 ->   ]
17:58:24.989 -> }

Should be:
17:58:24.953 -> output D1~: 
17:58:24.953 -> {"samples": [["2018-12-25 17:58:24.758523",[227.1036334078388]], ["2018-12-25 17:58:24.523437",[209.7977152168112]]]}

I have correct it and send you a pull request.
https://github.com/magneticchen/ArduTalk-for-NodeNCU

### CODE REVIEW

**Comment by iblislin** [comment]
cc @Jyneda

**Comment by Jyneda** [comment]
Under testing...

**Comment by TapiocaFox** [comment]
In this version, I used a dirty method which remove all the whitespaces of get_ret_str. It will not impact nodeMCU model. However, If the model has string type ODF the string's whitespace will be removed.

**Comment by iblislin** [comment]
please remove the file `.DS_Store` in this PR.

**Comment by TapiocaFox** [comment]
removed.

**Pull request merged**
